//! Test d'integration : worker mock Python + commandes transcript (save, exports).

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::time_utils::now_ms;
use crate::transcript_commands::{
    export_transcript, load_transcript_document, save_transcript_json,
};
use crate::{
    EditableSegment, ExportTimingRules, ExportTranscriptRequest, SaveTranscriptRequest,
    WorkerResult,
};

fn command_available(command: &str, base_args: &[&str]) -> bool {
    let mut probe = Command::new(command);
    probe.args(base_args).arg("--version");
    probe
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn resolve_test_python_command() -> Option<(String, Vec<String>)> {
    if let Ok(env_python) = std::env::var("WHISPERX_STUDIO_PYTHON") {
        let trimmed = env_python.trim();
        if !trimmed.is_empty() {
            return Some((trimmed.to_string(), vec![]));
        }
    }

    let candidates: [(&str, [&str; 0]); 1] = [("python", [])];
    for (command, args) in candidates {
        if command_available(command, &args) {
            return Some((command.to_string(), vec![]));
        }
    }

    if command_available("py", &["-3"]) {
        return Some(("py".into(), vec!["-3".into()]));
    }

    None
}

fn run_mock_worker_for_smoke(
    worker_path: &Path,
    input_path: &Path,
    output_dir: &Path,
    job_id: &str,
) -> Result<WorkerResult, String> {
    let (python_command, base_args) = resolve_test_python_command()
        .ok_or_else(|| "No usable Python command found for smoke test".to_string())?;

    let mut command = Command::new(&python_command);
    command
        .args(base_args)
        .arg(worker_path)
        .arg("--job-id")
        .arg(job_id)
        .arg("--input-path")
        .arg(input_path)
        .arg("--output-dir")
        .arg(output_dir)
        .arg("--mode")
        .arg("mock");

    let output = command
        .output()
        .map_err(|err| format!("Failed to execute worker smoke command: {err}"))?;

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!(
            "Mock worker failed with status {}. stdout='{stdout}' stderr='{stderr}'",
            output.status
        ));
    }

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();

    // Protocole JSON-lines : cherche une ligne {"type":"result",...}
    stdout
        .lines()
        .filter(|line| line.starts_with('{'))
        .find_map(|line| {
            let v: serde_json::Value = serde_json::from_str(line).ok()?;
            if v.get("type")?.as_str()? == "result" {
                serde_json::from_value::<WorkerResult>(v).ok()
            } else {
                None
            }
        })
        .ok_or_else(|| "Worker smoke run did not emit a result line (type=result)".to_string())
}

#[test]
fn smoke_mock_edit_export_flow() -> Result<(), String> {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or_else(|| "Unable to resolve workspace root".to_string())?
        .to_path_buf();
    let worker_path = workspace_root.join("python").join("worker.py");
    if !worker_path.exists() {
        return Err(format!(
            "Worker script not found for smoke test: {}",
            worker_path.display()
        ));
    }

    let temp_root = std::env::temp_dir().join(format!(
        "whisperx-smoke-{}-{}",
        now_ms(),
        std::process::id()
    ));
    let worker_output_dir = temp_root.join("worker-output");
    fs::create_dir_all(&worker_output_dir)
        .map_err(|err| format!("Unable to create smoke output dir: {err}"))?;

    let input_path = temp_root.join("mock-input.wav");
    fs::write(&input_path, b"smoke")
        .map_err(|err| format!("Unable to create smoke input media file: {err}"))?;

    let worker_result =
        run_mock_worker_for_smoke(&worker_path, &input_path, &worker_output_dir, "smoke-job")?;
    if worker_result.output_files.len() < 2 {
        return Err(format!(
            "Mock worker should emit at least 2 files, got {}",
            worker_result.output_files.len()
        ));
    }

    let aligned_path = worker_result
        .output_files
        .iter()
        .find(|path| path.ends_with(".aligned.json"))
        .cloned()
        .ok_or_else(|| "No aligned transcript generated by mock worker".to_string())?;

    let transcript = load_transcript_document(aligned_path.clone())?;
    if transcript.segments.len() < 2 {
        return Err("Mock transcript should contain at least 2 segments".into());
    }

    // Simulate editor changes with an intentionally unsorted + overlapping set
    // so export correction rules are exercised.
    let edited_segments = vec![
        EditableSegment {
            start: 1.7,
            end: 1.82,
            text: "sample transcript segment two cleaned".into(),
            speaker: Some("SPEAKER_01".into()),
            words: None,
        },
        EditableSegment {
            start: 0.0,
            end: 0.12,
            text: "sample transcript segment one curated".into(),
            speaker: Some("SPEAKER_00".into()),
            words: None,
        },
        EditableSegment {
            start: 0.1,
            end: 0.15,
            text: "bridge segment".into(),
            speaker: Some("SPEAKER_00".into()),
            words: None,
        },
    ];

    let saved_path = save_transcript_json(SaveTranscriptRequest {
        path: aligned_path.clone(),
        language: transcript.language.clone(),
        segments: edited_segments.clone(),
        overwrite: Some(false),
    })?;
    if !Path::new(&saved_path).exists() {
        return Err(format!("Edited transcript not saved: {saved_path}"));
    }

    let rules = ExportTimingRules {
        min_duration_sec: Some(0.4),
        min_gap_sec: Some(0.05),
        fix_overlaps: Some(true),
    };

    let mut exported: HashMap<String, String> = HashMap::new();
    let formats = ["json", "srt", "vtt", "txt"];
    for format in formats {
        let response = export_transcript(ExportTranscriptRequest {
            path: saved_path.clone(),
            language: transcript.language.clone(),
            segments: edited_segments.clone(),
            format: format.into(),
            rules: Some(rules.clone()),
        })?;
        if !Path::new(&response.output_path).exists() {
            return Err(format!(
                "Missing exported {format} file: {}",
                response.output_path
            ));
        }
        if response.report.total_adjustments == 0 {
            return Err(format!(
                "Expected export timing corrections for {format}, got none"
            ));
        }
        exported.insert(format.into(), response.output_path);
    }

    let txt_path = exported
        .get("txt")
        .ok_or_else(|| "Missing TXT export path in smoke test".to_string())?;
    let txt_content =
        fs::read_to_string(txt_path).map_err(|err| format!("Unable to read TXT export: {err}"))?;
    if !txt_content.contains("curated") {
        return Err("TXT export does not contain edited text marker".into());
    }

    let trace_path = temp_root.join("smoke-trace.txt");
    let trace_content = format!(
        "worker_output_dir={}\nsaved_path={}\njson={}\nsrt={}\nvtt={}\ntxt={}\n",
        worker_output_dir.display(),
        saved_path,
        exported.get("json").unwrap_or(&String::new()),
        exported.get("srt").unwrap_or(&String::new()),
        exported.get("vtt").unwrap_or(&String::new()),
        exported.get("txt").unwrap_or(&String::new())
    );
    fs::write(&trace_path, trace_content)
        .map_err(|err| format!("Unable to write smoke trace: {err}"))?;

    println!("Smoke trace: {}", trace_path.display());
    Ok(())
}
